export enum Commands {
  GET_STARTED = 'BOOTBOT_GET_STARTED',
  WRITE_FEEDBACK = 'ACCOUNT_WRITE_FEEDBACK',
  ORDERS = 'ORDERS',
  MAKE_ORDER_NOW = 'ORDERS_MAKE_ORDER_NOW',
  CREATED_ORDERS = 'ORDERS_CREATED_ORDERS',
  CURRENT_ORDERS = 'ORDERS_CURRENT_ORDERS',
  COMPLETED_ORDERS = 'ORDERS_COMPLETED_ORDERS',
  ORDERS_CANCEL = 'ORDERS_CANCEL',
  ACCOUNT = 'ACCOUNT',
  SHOW_CONTACT_INFORMATION = 'ACCOUNT_SHOW_CONTACT_INFORMATION',
  UPDATE_CONTACT_INFORMATION = 'ACCOUNT_UPDATE_CONTACT_INFORMATION',
  SHOW_DEFAULT_LOCATION = 'ACCOUNT_SHOW_DEFAULT_LOCATION',
  UPDATE_DEFAULT_LOCATION = 'ACCOUNT_UPDATE_DEFAULT_LOCATION'
}
